# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pyqt_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        MainWindow.setMinimumSize(QtCore.QSize(500, 400))
        MainWindow.setMaximumSize(QtCore.QSize(500, 400))
        MainWindow.setStyleSheet(
            "background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));"
        )
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.sValue = QtWidgets.QLabel(self.centralwidget)
        self.sValue.setGeometry(QtCore.QRect(360, 50, 41, 21))
        self.sValue.setStyleSheet(
            "border:none;\n" "color:rgba(0,0,0,1);\n" "background:rgba(0,0,0,0);\n" "font: 75 10pt"
        )

        self.Slider = QtWidgets.QSlider(self.centralwidget)
        self.Slider.setGeometry(QtCore.QRect(180, 50, 160, 21))
        self.Slider.setMouseTracking(False)
        self.Slider.setStyleSheet("border-radius:10px;\n" "background:rgba(0,0,0,0)")
        self.Slider.setMinimum(1)
        self.Slider.setSliderPosition(1)
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider.setObjectName("Slider")
        self.Slider.valueChanged.connect(self.value)

        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(200, 110, 93, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Text Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet(
            "border-radius: 12px;\n"
            "background:rgba(223,223,223,1);\n"
            "border:2px solid black;\n"
            ""
        )
        self.startButton.setObjectName("startButton")
        self.Adjust_sens = QtWidgets.QLabel(self.centralwidget)
        self.Adjust_sens.setGeometry(QtCore.QRect(30, 43, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic")
        font.setPointSize(10)
        self.Adjust_sens.setFont(font)
        self.Adjust_sens.setStyleSheet(
            "border:none;\n" "color:rgba(255,255,255,1);\n" "background:rgba(0,0,0,0)"
        )
        self.Adjust_sens.setObjectName("Adjust_sens")
        self.gridWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridWidget.setGeometry(QtCore.QRect(40, 220, 411, 80))
        self.gridWidget.setStyleSheet("background:rgba(0,0,0,0)")
        self.gridWidget.setObjectName("gridWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(1, 0, 1, 0)
        self.gridLayout_2.setHorizontalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.gridWidget)
        self.comboBox_3.setStyleSheet("background:rgba(223,223,223,1)")
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridWidget)
        self.comboBox_4.setStyleSheet("background:rgba(223,223,223,1)")
        self.comboBox_4.setObjectName("comboBox_4")
        self.gridLayout_2.addWidget(self.comboBox_4, 0, 2, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridWidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setAccessibleName("")
        self.comboBox.setStyleSheet("background:rgba(223,223,223,1)")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 0, 1, 1)
        self.horz_line = QtWidgets.QFrame(self.centralwidget)
        self.horz_line.setGeometry(QtCore.QRect(0, 170, 501, 20))
        self.horz_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.horz_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.horz_line.setObjectName("horz_line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiondfddfd = QtWidgets.QAction(MainWindow)
        self.actiondfddfd.setObjectName("actiondfddfd")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.sValue.setText(_translate("MainWindow", "0"))
        self.Adjust_sens.setText(_translate("MainWindow", "Adjust senstivity :"))
        self.comboBox.setCurrentText(_translate("MainWindow", "thumb"))
        self.comboBox.setItemText(0, _translate("MainWindow", "thumb"))
        self.comboBox.setItemText(1, _translate("MainWindow", "middle finger"))
        self.comboBox.setItemText(2, _translate("MainWindow", "ring finger"))
        self.comboBox.setItemText(3, _translate("MainWindow", "pinky"))
        self.actiondfddfd.setText(_translate("MainWindow", "dfddfd"))

    def value(self):
        value = self.Slider.value()
        self.sValue.setText(str(value))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
